In [2]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\ptlha\Documents\Math & Stat\health_records.csv")

df.head()

,record_id,age_group,age,weight,gender,region,smoking_status,exercise_frequency,bmi,blood_pressure,diabetes,hypertension,cholesterol_level,glucose_level,visit_date
0,HR0001,46-60,56,58,Male,West,Non-Smoker,Rarely,22.0,126.2,False,False,238.9,117.2,2026-02-23
1,HR0002,60+,69,86,Male,East,Smoker,Daily,33.3,145.4,False,True,271.8,106.8,2024-03-04
2,HR0003,46-60,46,53,Male,North,Non-Smoker,Weekly,19.8,118.9,False,False,173.6,94.1,2026-08-02
3,HR0004,26-35,32,93,Male,East,Non-Smoker,Weekly,36.6,135.5,False,False,219.4,91.3,2025-11-16
4,HR0005,46-60,60,57,Female,North,Non-Smoker,Weekly,19.9,125.9,False,False,173.4,80.9,2025-09-21

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   record_id           500 non-null    str
 1   age_group           500 non-null    str
 2   age                 500 non-null    int64
 3   weight              500 non-null    int64
 4   gender              500 non-null    str
 5   region              500 non-null    str
 6   smoking_status      500 non-null    str
 7   exercise_frequency  500 non-null    str
 8   bmi                 500 non-null    float64
 9   blood_pressure      500 non-null    float64
 10  diabetes            500 non-null    bool
 11  hypertension        500 non-null    bool
 12  cholesterol_level   500 non-null    float64
 13  glucose_level       500 non-null    float64
 14  visit_date          500 non-null    str
dtypes: bool(2), float64(4), int64(2), str(7)
memory usage: 74.1 KB

In [5]:
df.isnull().sum()

record_id             0
age_group             0
age                   0
weight                0
gender                0
region                0
smoking_status        0
exercise_frequency    0
bmi                   0
blood_pressure        0
diabetes              0
hypertension          0
cholesterol_level     0
glucose_level         0
visit_date            0
dtype: int64

In [6]:
df.describe()

,age,weight,bmi,blood_pressure,cholesterol_level,glucose_level
count,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,44.732000,70.302000,25.077600,131.06860,202.173000,92.019600
std,15.239707,13.644601,5.801242,13.28209,29.886437,13.650987
min,18.000000,42.000000,12.600000,96.40000,125.500000,55.000000
25%,32.000000,61.000000,21.000000,122.67500,181.075000,84.125000
50%,45.000000,70.000000,24.800000,131.20000,202.100000,92.300000
75%,57.000000,80.000000,28.500000,140.22500,222.800000,100.225000
max,70.000000,114.000000,49.000000,167.80000,285.000000,143.500000

# Part A - Theoretical Foundation

## 1. What is Inferential Statistics?

Inferential statistics is the process of using sample data to draw conclusions or make estimates about a larger population.

## 2. What is Hypothesis Testing?

Hypothesis testing is a statistical method used to determine whether there is enough evidence to reject a null hypothesis. Its main components include the null hypothesis, alternative hypothesis, significance level, test statistic and p-value.

## 3. Confidence Interval and Critical Value

A confidence interval gives a range of plausible values for a population parameter at a selected confidence level. A critical value is a cutoff point used to determine whether a test statistic falls in the rejection region.

## 4. P-value

A p-value is the probability of obtaining a result at least as extreme as the observed result when the null hypothesis is true. A small p-value provides evidence against the null hypothesis.

## 5. Type I and Type II Errors

Type I error occurs when a true null hypothesis is rejected. Type II error occurs when a false null hypothesis is not rejected.

## 6. Statistical Tests

A z-test is used for mean comparison when population variance is known or for sufficiently large samples. A t-test is commonly used when population variance is unknown. A chi-square test examines association between categorical variables. ANOVA compares means across three or more groups.

## 7. Covariance

Covariance measures the direction in which two numerical variables vary together. Positive covariance indicates that variables tend to increase together, while negative covariance indicates opposite movement.

## 8. Correlation

Correlation measures the strength and direction of the linear relationship between two numerical variables. Its value ranges from -1 to +1.

# Part B - Data Analysis and Statistical Testing

## 1. Hypothesis Testing
### Hypothesis 1: Smoking and Diabetes

H₀: Smoking has no effect on Diabetes prevalence.

H₁: Smoking affects Diabetes prevalence.

### Hypothesis 2: Exercise and Diabetes

H₀: Exercise frequency has no effect on Diabetes prevalence.

H₁: Exercise frequency affects Diabetes prevalence.

## 2. 95% Confidence Interval for Age

A 95% confidence interval is calculated to estimate the range of plausible values for the population mean age.

In [7]:
age_mean = df["age"].mean()

age_sem = stats.sem(df["age"])

confidence_interval = stats.t.interval(
    confidence=0.95,
    df=len(df["age"]) - 1,
    loc=age_mean,
    scale=age_sem
)

print("Mean Age:", age_mean)
print("95% Confidence Interval:", confidence_interval)

Mean Age: 44.732
95% Confidence Interval: (np.float64(43.392957501932855), np.float64(46.07104249806714))

In [8]:
print(
    "Interpretation: We are 95% confident that the population mean age lies within the calculated confidence interval."
)

Interpretation: We are 95% confident that the population mean age lies within the calculated confidence interval.

## 3. Critical Value and P-value

The critical value is used as a cutoff for deciding whether a statistical result falls in the rejection region. The p-value helps determine whether there is sufficient evidence against H₀.

In [9]:
alpha = 0.05

degrees_of_freedom = len(df["age"]) - 1

critical_value = stats.t.ppf(1 - alpha / 2,degrees_of_freedom)

print("Significance Level:", alpha)
print("Degrees of Freedom:", degrees_of_freedom)
print("Critical Value:", critical_value)

Significance Level: 0.05
Degrees of Freedom: 499
Critical Value: 1.9647293909876886

## 4. Independent t-test: BMI of Diabetes vs Non-Diabetes Groups

#### H₀-There is no significant difference in mean BMI between diabetes and non-diabetes groups.

#### H₁-There is a significant difference in mean BMI between diabetes and non-diabetes groups.

#### Significance Level α = 0.05

In [10]:
diabetes_bmi = df[df["diabetes"] == True]["bmi"]
non_diabetes_bmi = df[df["diabetes"] == False]["bmi"]

In [11]:
print("Mean BMI - Diabetes:", diabetes_bmi.mean())
print("Mean BMI - Non-Diabetes:", non_diabetes_bmi.mean())

Mean BMI - Diabetes: 28.98695652173913
Mean BMI - Non-Diabetes: 24.88909853249476

In [12]:
t_stat, p_value_t = stats.ttest_ind(diabetes_bmi,non_diabetes_bmi,equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_value_t)

t-statistic: 3.1460700855951487
p-value: 0.004390083412718215

In [13]:
if p_value_t < 0.05:
    print("Decision: Reject H0")
    print("Interpretation: There is a statistically significant difference in mean BMI between the two groups.")
else:
    print("Decision: Fail to reject H0")
    print("Interpretation: There is not enough evidence of a significant difference in mean BMI between the two groups.")

Decision: Reject H0
Interpretation: There is a statistically significant difference in mean BMI between the two groups.

## 5. Chi-square Test: Smoking Status vs Hypertension

#### H₀-Smoking status has no association with hypertension.

#### H₁-Smoking status has an association with hypertension.

#### Significance Level α = 0.05

In [14]:
table = pd.crosstab(
    df["smoking_status"],
    df["hypertension"]
)

print(table)

hypertension    False  True
smoking_status
Former Smoker      72     34
Non-Smoker        227     58
Smoker             81     28

In [15]:
chi2, p_value, dof, expected = stats.chi2_contingency(table)

print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)

Chi-square statistic: 6.040733002999074
p-value: 0.04878333591947522
Degrees of freedom: 2

In [16]:
if p_value < 0.05:
    print("Decision: Reject H0")
    print("Interpretation: There is a statistically significant association between smoking status and hypertension.")
else:
    print("Decision: Fail to reject H0")
    print("Interpretation: There is not enough statistical evidence of an association between smoking status and hypertension.")

Decision: Reject H0
Interpretation: There is a statistically significant association between smoking status and hypertension.

## 6. ANOVA Test: BMI Across Age Groups

#### H₀-There is no significant difference in mean BMI among the age groups.

#### H₁-At least one age group has a significantly different mean BMI.

#### Significance Level α = 0.05

In [17]:
group_18_25 = df[df["age_group"] == "18-25"]["bmi"]
group_26_35 = df[df["age_group"] == "26-35"]["bmi"]
group_36_45 = df[df["age_group"] == "36-45"]["bmi"]
group_46_60 = df[df["age_group"] == "46-60"]["bmi"]
group_60_plus = df[df["age_group"] == "60+"]["bmi"]

In [18]:
f_stat, p_value_anova = stats.f_oneway(
    group_18_25,
    group_26_35,
    group_36_45,
    group_46_60,
    group_60_plus
)

print("F-statistic:", f_stat)
print("p-value:", p_value_anova)

F-statistic: 0.3805930914461578
p-value: 0.822541328096908

In [19]:
if p_value_anova < 0.05:
    print("Decision: Reject H0")
    print("Interpretation: At least one age group has a significantly different mean BMI.")
else:
    print("Decision: Fail to reject H0")
    print("Interpretation: There is not enough evidence that mean BMI differs across age groups.")

Decision: Fail to reject H0
Interpretation: There is not enough evidence that mean BMI differs across age groups.

## 7. Covariance: Age vs BMI

Covariance measures the direction in which Age and BMI vary together.

In [20]:
covariance = df["age"].cov(df["bmi"])

print("Covariance between Age and BMI:", covariance)

Covariance between Age and BMI: -1.6623278557114243

Interpretation: The covariance between Age and BMI is negative, indicating a negative direction of variation in this sample. However, covariance alone does not determine the strength of the relationship.

## 7. Correlation: Age vs BMI

Correlation measures the strength and direction of the linear relationship between Age and BMI.

In [21]:
correlation = df["age"].corr(df["bmi"])

print("Correlation between Age and BMI:", correlation)

Correlation between Age and BMI: -0.01880265120636106

Interpretation: The correlation between Age and BMI is approximately -0.019, indicating a very weak or almost negligible linear relationship between the two variables.

# ----- FINAL STATISTICAL RESULTS -----

In [24]:
print("\n1. T-TEST")
print("T-Statistic:", t_stat)
print("P-Value:", p_value_t)

if p_value_t < 0.05:
    print("Decision: Reject H0")
else:
    print("Decision: Accept H0")


print("\n2. CHI-SQUARE TEST")
print("Chi-Square:", chi2)
print("P-Value:", p_value)

if p_value < 0.05:
    print("Decision: Reject H0")
else:
    print("Decision: Accept H0")


print("\n3. ANOVA")
print("F-Statistic:", f_stat)
print("P-Value:", p_value_anova)

if p_value_anova < 0.05:
    print("Decision: Reject H0")
else:
    print("Decision: Accept H0")


print("\n4. COVARIANCE")
print("Covariance:", covariance)


print("\n5. CORRELATION")
print("Correlation:", correlation)

1. T-TEST
T-Statistic: 3.1460700855951487
P-Value: 0.004390083412718215
Decision: Reject H0

2. CHI-SQUARE TEST
Chi-Square: 6.040733002999074
P-Value: 0.04878333591947522
Decision: Reject H0

3. ANOVA
F-Statistic: 0.3805930914461578
P-Value: 0.822541328096908
Decision: Accept H0

4. COVARIANCE
Covariance: -1.6623278557114243

5. CORRELATION
Correlation: -0.01880265120636106